// Build pipeline for the Radius Canvas extension.
//
// Bundles the TypeScript/ESM source under adapters/canvas/src (which imports the
// UI-agnostic TypeScript core from radius-core) into the single
// runtime-loadable artifact the Copilot canvas loader runs:
//
//   .github/radius/extension.mjs
//
// The Copilot SDK is marked external so its auto-resolved import is preserved in
// the output (the loader resolves @github/copilot-sdk at runtime).

import * as esbuild from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { copyFileSync, existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..");

const isWatch = process.argv.includes("--watch");
// --install copies the build output into the locally installed extension dir and
// drops a `.dev-reload` sentinel so the extension's dev self-reloader arms. The
// self-reloader watches the installed extension.mjs and gracefully restarts the
// extension when it changes, so a fresh build hot-reloads. Combined with --watch
// this gives edit-source → rebuild → copy → self-reload end to end.
//
// NOTE: the installed extension is user-scoped and shared by every session on
// this machine, so a reload briefly (~1s) reconnects the extension in ALL
// sessions. Do interactive canvas testing in a session separate from the one you
// edit in, so the reconnect blip never interrupts active canvas use.
const isInstall = process.argv.includes("--install");

const outfile = join(repoRoot, ".github", "radius", "extension.mjs");

// Where the extension is installed locally. Override with RADIUS_CANVAS_INSTALL_PATH.
const installPath =
  process.env.RADIUS_CANVAS_INSTALL_PATH ||
  join(homedir(), ".copilot", "extensions", "radius-canvas", "extension.mjs");

function installToLocal() {
  try {
    const installDir = dirname(installPath);
    mkdirSync(installDir, { recursive: true });
    // Write atomically: copy to a temp file in the same dir, then rename over the
    // target. rename() is atomic on the same filesystem, so the self-reloader's
    // watcher never observes a half-written file (which would import as a
    // truncated module and crash the respawned process with no clean error).
    const tmp = `${installPath}.tmp-${process.pid}`;
    copyFileSync(outfile, tmp);
    renameSync(tmp, installPath);
    // Arm the dev self-reloader in the installed copy (idempotent).
    const sentinel = join(installDir, ".dev-reload");
    if (!existsSync(sentinel)) writeFileSync(sentinel, "dev\n");
    console.log(`[canvas] installed → ${installPath}`);
  } catch (e) {
    console.error(`[canvas] install copy failed: ${e?.message || e}`);
  }
}

// esbuild plugin that runs installToLocal after every (re)build, so it fires on
// each watch rebuild too — the installed-file write is what the host detects.
const installPlugin = {
  name: "install-to-local",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length === 0) installToLocal();
    });
  },
};

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [join(__dirname, "src", "extension.mjs")],
  outfile,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node18",
  // The SDK is resolved by the loader at runtime — never bundle it.
  external: ["@github/copilot-sdk", "@github/copilot-sdk/extension"],
  legalComments: "none",
  logLevel: "info",
  banner: {
    js: "// AUTO-GENERATED by adapters/canvas/build.mjs — do not edit by hand.\n// Source: adapters/canvas/src + radius-core. Run `npm run build:canvas`.",
  },
  plugins: isInstall ? [installPlugin] : [],
};

if (isWatch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log("[canvas] watching for changes…");
} else {
  await esbuild.build(options);
  console.log("[canvas] built .github/radius/extension.mjs");
  if (isInstall) installToLocal();
}
