// Build pipeline for the Radius Canvas extension.
//
// Bundles the TypeScript/ESM source under adapters/canvas/src (which imports the
// UI-agnostic TypeScript core from radius-core) into the single
// runtime-loadable artifact the Copilot canvas loader runs:
//
//   .github/radius/extension.mjs
//
// The Copilot SDK is marked external so its auto-resolved import is preserved in
// the output (the loader resolves @github/copilot-sdk at runtime).

import * as esbuild from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..");

const isWatch = process.argv.includes("--watch");

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [join(__dirname, "src", "extension.mjs")],
  outfile: join(repoRoot, ".github", "radius", "extension.mjs"),
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node18",
  // The SDK is resolved by the loader at runtime — never bundle it.
  external: ["@github/copilot-sdk", "@github/copilot-sdk/extension"],
  legalComments: "none",
  logLevel: "info",
  banner: {
    js: "// AUTO-GENERATED by adapters/canvas/build.mjs — do not edit by hand.\n// Source: adapters/canvas/src + radius-core. Run `npm run build:canvas`.",
  },
};

if (isWatch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log("[canvas] watching for changes…");
} else {
  await esbuild.build(options);
  console.log("[canvas] built .github/radius/extension.mjs");
}
