// Build pipeline for the Radius Canvas extension.
//
// Bundles the TypeScript/ESM source under adapters/canvas/src (which imports the
// UI-agnostic TypeScript core from radius-core) into the single
// runtime-loadable artifact the Copilot canvas loader runs:
//
//   plugins/radius/extension.mjs
//
// The Copilot SDK is marked external so its auto-resolved import is preserved in
// the output (the loader resolves @github/copilot-sdk at runtime).

import * as esbuild from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  renameSync,
  rmSync
} from "node:fs";
import { homedir } from "node:os";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..");

const isWatch = process.argv.includes("--watch");
// --install copies the build output into the locally installed extension dir the
// host loads. It does NOT arm any auto hot-reload: the installed extension is
// user-scoped and shared by every session on this machine, so restarting it on a
// rebuild would tear down ALL sessions (they'd appear to "constantly stop"). New
// code is instead picked up when a session next starts a fresh process. A
// developer who explicitly wants hot-reload for a given process can set
// RADIUS_CANVAS_DEV=1 (see src/extension.mjs); it is intentionally not enabled by
// an on-disk sentinel, which would persist and re-enable the destructive behavior
// for everyone.
const isInstall = process.argv.includes("--install");

const outfile = join(repoRoot, "plugins", "radius", "extension.mjs");

// Where the extension is installed locally. Override with RADIUS_CANVAS_INSTALL_PATH.
// The host loads this canvas as the "radius" extension (see plugins/radius/package.json),
// so install into that directory — not a separate "radius-canvas" dir the host never loads.
const installPath =
  process.env.RADIUS_CANVAS_INSTALL_PATH ||
  join(homedir(), ".copilot", "extensions", "radius", "extension.mjs");

function installToLocal() {
  try {
    const installDir = dirname(installPath);
    mkdirSync(installDir, { recursive: true });
    // Write atomically: copy to a temp file in the same dir, then rename over the
    // target. rename() is atomic on the same filesystem, so a watcher never
    // observes a half-written file (which would import as a truncated module and
    // crash a respawned process with no clean error).
    const tmp = `${installPath}.tmp-${process.pid}`;
    copyFileSync(outfile, tmp);
    renameSync(tmp, installPath);
    // Remove any legacy `.dev-reload` sentinel from older installs so it can't
    // keep the (now opt-in) self-reloader armed on this machine.
    try {
      const sentinel = join(installDir, ".dev-reload");
      if (existsSync(sentinel)) rmSync(sentinel);
    } catch {
      /* best-effort cleanup */
    }
    console.log(`[canvas] installed → ${installPath}`);
  } catch (e) {
    console.error(`[canvas] install copy failed: ${e?.message || e}`);
  }
}

// In watch mode, copy to the install path after every rebuild so a running
// dev process (with RADIUS_CANVAS_DEV=1) can pick it up. One-shot installs use
// the trailing call below instead, so the file is written exactly once.
const installPlugin = {
  name: "install-to-local",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length === 0) installToLocal();
    });
  }
};

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [join(__dirname, "src", "extension.mjs")],
  outfile,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node18",
  // The SDK is resolved by the loader at runtime — never bundle it.
  external: ["@github/copilot-sdk", "@github/copilot-sdk/extension"],
  // Inline the radius-app-bicep skill Markdown (SKILL.md + references) as text
  // so the extension ships the authoritative skill content even when installed
  // without the sibling plugins/radius/skills/ tree. See src/skill.mjs.
  loader: { ".md": "text" },
  legalComments: "none",
  logLevel: "info",
  banner: {
    js: "// AUTO-GENERATED by adapters/canvas/build.mjs — do not edit by hand.\n// Source: adapters/canvas/src + radius-core. Run `npm run build:canvas`."
  },
  // Only wire the after-build install hook for watch mode; a one-shot build
  // installs via the trailing call below, so the file is written exactly once
  // (a double write would trigger two watcher events in any dev process).
  plugins: isInstall && isWatch ? [installPlugin] : []
};

if (isWatch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log("[canvas] watching for changes…");
} else {
  await esbuild.build(options);
  console.log("[canvas] built plugins/radius/extension.mjs");
  if (isInstall) installToLocal();
}
