import { describe, it, expect } from "vitest";
import {
  WORKFLOW_MANAGED_PARAMS,
  parseBicepParams,
  appParams,
  resolveDeployParams,
  partitionParams,
  buildDeployRadCommand,
  buildAppGraphRadCommand,
} from "./bicep.mjs";

// A representative app.bicep as generated by the extension: `environment` and
// `application` are injected by the rad CLI, `image` is supplied by the deploy
// workflow, `registryUsername`/`registryPassword` are the OCI registry creds the
// workflow injects from the runner (github.actor / GITHUB_TOKEN), and `password`
// is a genuine app secret.
const APP_BICEP = `extension radius

param environment string
param application string
@secure()
param password string
@description('The full container image reference to build and push.')
param image string
@description('Username for the OCI registry the containerImages recipe pushes to.')
param registryUsername string
@secure()
param registryPassword string

resource db 'Radius.Data/mySqlDatabases@2025-08-01-preview' = {
  name: 'mysql'
  properties: {
    environment: environment
    application: application
    password: password
  }
}
`;

describe("WORKFLOW_MANAGED_PARAMS", () => {
  it("treats environment, application, and image as CLI/workflow injected", () => {
    // `application` must be present: rad injects it at deploy time, so the
    // extension must never auto-generate a value or pass --parameters application.
    expect(WORKFLOW_MANAGED_PARAMS.has("environment")).toBe(true);
    expect(WORKFLOW_MANAGED_PARAMS.has("application")).toBe(true);
    expect(WORKFLOW_MANAGED_PARAMS.has("image")).toBe(true);
  });

  it("treats the registry credentials as runner-injected by the workflow", () => {
    // registryUsername/registryPassword resolve to the runner's github.actor /
    // GITHUB_TOKEN, which only exist inside the Actions runner — the workflow
    // injects them. The extension must never autogenerate them, or the random
    // values would collide with the workflow-injected --parameters and break the
    // image push.
    expect(WORKFLOW_MANAGED_PARAMS.has("registryUsername")).toBe(true);
    expect(WORKFLOW_MANAGED_PARAMS.has("registryPassword")).toBe(true);
  });
});

describe("appParams", () => {
  it("excludes the workflow/CLI managed params", () => {
    const names = appParams(APP_BICEP).map((p) => p.name);
    expect(names).toEqual(["password"]);
    expect(names).not.toContain("application");
    expect(names).not.toContain("environment");
    expect(names).not.toContain("image");
    expect(names).not.toContain("registryUsername");
    expect(names).not.toContain("registryPassword");
  });
});

describe("resolveDeployParams", () => {
  it("never auto-generates a value for the application parameter", () => {
    const resolved = resolveDeployParams(parseBicepParams(APP_BICEP));
    // Regression guard: auto-generating application=<random> both corrupts the
    // app name and makes rad deploy reject templates that don't declare an
    // `application` parameter ("supplied but do not correspond to any parameters
    // defined in the template: 'application'").
    expect(resolved.application).toBeUndefined();
    expect(resolved.environment).toBeUndefined();
    expect(resolved.image).toBeUndefined();
    expect(typeof resolved.password).toBe("string");
    expect(resolved.password.length).toBeGreaterThan(0);
  });

  it("never auto-generates the registry credentials", () => {
    // The workflow injects these from the runner; a random value here would land
    // in RADIUS_DEPLOY_PARAMS / the deploy command and break the image push.
    const resolved = resolveDeployParams(parseBicepParams(APP_BICEP));
    expect(resolved.registryUsername).toBeUndefined();
    expect(resolved.registryPassword).toBeUndefined();
  });
});

describe("buildDeployRadCommand", () => {
  it("does not pass application as a --parameters value", () => {
    const parsed = appParams(APP_BICEP);
    const resolved = resolveDeployParams(parsed);
    const { public: publicParams } = partitionParams(parsed, resolved);
    const cmd = buildDeployRadCommand(".radius/app.bicep", "prod", publicParams);
    expect(cmd).toBe("deploy .radius/app.bicep --environment prod");
    expect(cmd).not.toContain("application");
  });

  it("does not inline the registry credentials into the deploy command", () => {
    // registryUsername is not @secure, so without WORKFLOW_MANAGED_PARAMS it
    // would land in the public bucket and be inlined here, colliding with the
    // workflow-injected --parameters registryUsername.
    const parsed = appParams(APP_BICEP);
    const resolved = resolveDeployParams(parsed);
    const { public: publicParams } = partitionParams(parsed, resolved);
    const cmd = buildDeployRadCommand(".radius/app.bicep", "prod", publicParams);
    expect(cmd).not.toContain("registryUsername");
    expect(cmd).not.toContain("registryPassword");
  });

});

describe("buildAppGraphRadCommand", () => {
  it("includes the required preview and icon flags", () => {
    expect(buildAppGraphRadCommand("my-app")).toBe(
      "app graph --application my-app --preview --include-icons",
    );
  });
});
