import { describe, it, expect } from "vitest";
import {
  WORKFLOW_MANAGED_PARAMS,
  parseBicepParams,
  appParams,
  resolveDeployParams,
  partitionParams,
  buildDeployRadCommand,
} from "./bicep.mjs";

// A representative app.bicep as generated by the extension: `environment` and
// `application` are injected by the rad CLI, `image` is supplied by the deploy
// workflow, and `password` is a genuine app secret.
const APP_BICEP = `extension radius

param environment string
param application string
@secure()
param password string
@description('The full container image reference to build and push.')
param image string

resource db 'Radius.Data/mySqlDatabases@2025-08-01-preview' = {
  name: 'mysql'
  properties: {
    environment: environment
    application: application
    password: password
  }
}
`;

describe("WORKFLOW_MANAGED_PARAMS", () => {
  it("treats environment, application, and image as CLI/workflow injected", () => {
    // `application` must be present: rad injects it at deploy time, so the
    // extension must never auto-generate a value or pass --parameters application.
    expect(WORKFLOW_MANAGED_PARAMS.has("environment")).toBe(true);
    expect(WORKFLOW_MANAGED_PARAMS.has("application")).toBe(true);
    expect(WORKFLOW_MANAGED_PARAMS.has("image")).toBe(true);
  });
});

describe("appParams", () => {
  it("excludes the workflow/CLI managed params", () => {
    const names = appParams(APP_BICEP).map((p) => p.name);
    expect(names).toEqual(["password"]);
    expect(names).not.toContain("application");
    expect(names).not.toContain("environment");
    expect(names).not.toContain("image");
  });
});

describe("resolveDeployParams", () => {
  it("never auto-generates a value for the application parameter", () => {
    const resolved = resolveDeployParams(parseBicepParams(APP_BICEP));
    // Regression guard: auto-generating application=<random> both corrupts the
    // app name and makes rad deploy reject templates that don't declare an
    // `application` parameter ("supplied but do not correspond to any parameters
    // defined in the template: 'application'").
    expect(resolved.application).toBeUndefined();
    expect(resolved.environment).toBeUndefined();
    expect(resolved.image).toBeUndefined();
    expect(typeof resolved.password).toBe("string");
    expect(resolved.password.length).toBeGreaterThan(0);
  });
});

describe("buildDeployRadCommand", () => {
  it("does not pass application as a --parameters value", () => {
    const parsed = appParams(APP_BICEP);
    const resolved = resolveDeployParams(parsed);
    const { public: publicParams } = partitionParams(parsed, resolved);
    const cmd = buildDeployRadCommand(".radius/app.bicep", "prod", publicParams);
    expect(cmd).toBe("deploy .radius/app.bicep --environment prod");
    expect(cmd).not.toContain("application");
  });
});
