import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "src/deploy-artifacts.test.ts",
      "src/credential-provenance-store.test.ts",
      "src/operation-store.test.ts",
      "../adapter-shared/src/lifecycle/source-access*.test.ts",
      "../adapter-shared/src/lifecycle/{application-read*,environment-read*,workspace-source*,deployed-application-read*}.test.ts",
      "../adapter-shared/src/lifecycle/github-source*.test.ts",
      "../adapter-shared/src/lifecycle/graph-execution*.test.ts",
      "../adapter-shared/src/lifecycle/definition-*.test.ts",
      "../adapter-shared/src/lifecycle/{workflow-execution,execution-evidence}.test.ts",
      "../adapter-shared/src/lifecycle/environment-configuration.test.ts",
      "../core/src/lifecycle/{credentials,environments,environment-configuration,configuration-authority}.test.ts",
      "../core/src/lifecycle/{deployment,operation-reads,execution-result}.test.ts",
      "../core/src/lifecycle/{repair,cancellation}.test.ts",
      "../adapter-shared/src/rad-process-{isolation,boundary}.test.ts",
      "../core/src/lifecycle/{operations,actions,discovery*,environments-read*,graphs,authoring,definition-validation,validation-policy}.test.ts",
      "src/runtime/{lifecycle-*,create-lifecycle-binding}.test.ts",
      "src/runtime/{graph-reader,create-radius-canvas*,create-radius-tools,create-radius-extension}.test.ts",
      "src/runtime/create-discovery-context*.test.ts",
      "src/runtime/discovery-*.test.ts",
      "test/integration/runtime/lifecycle-{foundation,discovery,graphs,authoring,deployment}.test.ts",
      "test/integration/runtime/lifecycle-environments.test.ts",
      "test/integration/runtime/lifecycle-controls.test.ts",
      "src/server/services/lifecycle-controls-http.test.ts",
      "src/browser/lifecycle-controls.test.ts",
      "src/server/services/lifecycle-environment*.test.ts",
      "src/promote-app-model*.test.ts",
      "test/support/lifecycle-authoring.test.ts",
      "test/support/artifact/harness.test.ts",
      "src/gh*.test.ts",
      "src/workspace.test.ts",
      "src/server/create-canvas-server.test.ts",
      "src/server/routes/{graphs-planning*,graph-workflows*}.test.ts",
      "src/server/services/discovery*.test.ts",
      "src/server/services/retained-monitoring.test.ts",
      "src/server/services/github-environment-variable-rollback.test.ts",
      "src/browser/{heartbeat,lifecycle,repositories}.test.ts",
      "src/browser/environment/**/*.test.ts",
      "src/browser/pages/**/*.test.ts",
      "src/browser/graph/**/*.test.ts",
      "test/e2e-cloud/support/{cloud-command-port,cloud-fixture}.test.ts",
      "test/e2e/support/**/*.test.ts",
      "test/integration/http/**/*.test.ts"
    ],
    environment: "node",
    testTimeout: 15_000
  }
});
